### ISSUE TITLE
Hello World fails

### ISSUE THREAD

**Issue by rdebath** [ids1024/isbfc#1]
Commit 1ae6991 introduced a change that caused this 'Hello World!' program to display 
`Hello Segmentation fault`

``` brainfuck
>++++++++[-<+++++++++>]<.>[][<-]>+>-[+]++>++>+++[>[->+++<<+++>]<<]>-----.
>->+++..+++.>-.<<+[>[+>+]>>]<--------------.>>.+++.------.--------.>+.>+.
```

If the section `[>[+>+]>>]` is removed it completes successfully.

**Comment by ids1024** [comment]
Hm, the problem seems to be in `>->+++`.

With this optimization removed, this produces the intermediate representation:

```
move(offset=1)
add(offset=0, value=-1)
move(offset=1)
add(offset=0, value=3)
```

Which correctly compiles to this assembly:

``` asm
movq %r12, (%rbx)
add $8, %rbx
movq (%rbx), %r12
dec %r12
movq %r12, (%rbx)
add $8, %rbx
movq (%rbx), %r12
add $3, %r12
```

Add back the optimization, and `optimize()` results in this correct IR code:

```
add(offset=1, value=-1)
move(offset=2)
add(offset=0, value=3)
```

Which, for some reason, compiles to this:

``` asm
movq %r12, (%rbx)
add $16, %rbx
movq (%rbx), %r12
```

The `add` is not handled! I don't know why...

Edit: Wait, I'm looking at the wrong assembly code...

**Comment by ids1024** [comment]
Actually, the above post is wrong. I have no idea why this is failing.

Anyway, the immediate cause for the segfault is `[+>+]` running without termination. The actual problem must be something before that...

Edit: Hm, the diff of the generated assembly code looks fine...

**Comment by rdebath** [comment]
Okay, it took me a few minutes to realise what I was looking at.

Your problem is that the assembler's defaults are tailored to the current C interpretation of what '64bit' means. This is more like an old style MS-DOS 32bit-large-model.

This means that the `add`, `sub`, `inc` etc default to 32bit operations if nothing tells them different.
So this is 64bit ...

``` assembly
 add $3, %r12
```

But this is 32bit

``` assembly
add $1, 8(%rbx)
```

Add in a scatter of `q` modifiers and it seems fine.

**Comment by ids1024** [comment]
Thanks! Needless to say, I have limited experience with assembly.

**Comment by rdebath** [comment]
The [tests run now](https://rawgit.com/rdebath/Brainfuck/results/index.html); Looking good, after I increased the tape length to 1.6M.

**Comment by ids1024** [comment]
@rdebath That looks like a pretty good test suite. How can I automatically run all the tests on my own system? I don't see a script for that in https://github.com/rdebath/Brainfuck...

**Comment by rdebath** [comment]
okaaaay, 

I've uploaded a copy of my "transport blob" to https://github.com/rdebath/test/tree/bfresults I use it to build my code and some of the _competitors_ on "other" machines. Programs that fail the initial "Hello world" will leave files in `/tmp/hell-fail-*`, otherwise just let it run and everything will be dumped into `Testrun`. If you want to run a single interpreter use `bin/bftest "name"`.

If everything runs it'll probably take a few days.
